version: '3'
services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - alas
    volumes:
      - redis-data:/data
  api:
    build: "../"
    environment:
      LISTEN_ADDR: "${LISTEN_ADDR}"
      CACHE_TTL: "${CACHE_TTL}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_DATABASE: "${REDIS_DATABASE}"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - alas
networks:
  alas:
volumes:
  redis-data:
